install.packages(c("devtools", "selectr", "aod", "plm", "ggplot2"))
library(devtools)
install_github('ramnathv/rCharts@dev', dependencies=TRUE)
install_github('ramnathv/rMaps', dependencies=TRUE)
install_github("choroplethr", "trulia", dependencies=TRUE)
